// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://dtyzunvgbmnheqbubhef.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR0eXp1bnZnYm1uaGVxYnViaGVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg3NzUyNTQsImV4cCI6MjA4NDM1MTI1NH0.M89K2IMTLhx5puWJd5FCQqipqE3qiBHm7p9s6VE6AOQ";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);